### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by rexer78** [ccoors/valegram-bot#1]
Hi i love your bot, you can write a guide to install? i have this error when i try to run the bot
```
/mnt/data/valegram-bot/valegram-bot.js: line 1: syntax error near unexpected token `)'
/mnt/data/valegram-bot/valegram-bot.js: line 1: `()='
```

you can help me?
thank you

**Comment by ccoors** [comment]
You cannot execute the file directly, it needs to be started with the Valetudo binary. The README contains everything you need to know.
